### ISSUE TITLE
Shard warning on Crystal 1.2.2

### ISSUE THREAD

**Issue by jwoertink** [NeuraLegion/sec_tester#3]
I get this:

> Shard "sec_tester" may be incompatible with Crystal 1.2.2

I'm using version 1.1.2 of the shard.

**Comment by bararchy** [comment]
@jwoertink it's the new `shards` feature in place. the `shards.yml` file has `crystal: 1.3.2` so if you have older Crystal it might show the warning. but it should work anyways. 

Does the warning break your shards update process?

**Comment by jwoertink** [comment]
Ah, ok. Everything works. I just noticed it started showing so figured i'd report just in case.

**Comment by bararchy** [comment]
@jwoertink fixed in v1.1.3 :) 

https://github.com/NeuraLegion/sec_tester/commit/bf4c43bf706a2289624c1c2547156e1e06784b37

**Comment by jwoertink** [comment]
nice! Thanks :smile:
